//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use super::sea_orm_active_enums::ContentType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "content")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub content_id: i32,
    pub title: String,
    pub content_type: ContentType,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sentence::Entity")]
    Sentence,
}

impl Related<super::sentence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sentence.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
