//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::content::Entity as Content;
pub use super::post::Entity as Post;
pub use super::sentence::Entity as Sentence;
pub use super::sentence_word::Entity as SentenceWord;
pub use super::user::Entity as User;
pub use super::user_word_progress::Entity as UserWordProgress;
pub use super::word::Entity as Word;
